// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGxDAdbLo46tjRrTb_oGuvG1a_UUpeU9A',
    appId: '1:357186491755:web:68253ca8e4d304ce9c282e',
    messagingSenderId: '357186491755',
    projectId: 'fir-login-c3535',
    authDomain: 'fir-login-c3535.firebaseapp.com',
    storageBucket: 'fir-login-c3535.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWyEQtm7kezf03Fytpf97Zb5xnThJvwJc',
    appId: '1:357186491755:android:65c0c193bec80a489c282e',
    messagingSenderId: '357186491755',
    projectId: 'fir-login-c3535',
    storageBucket: 'fir-login-c3535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCij3-X18MRhfUQF7J09kXjK2V4EgRSWyU',
    appId: '1:357186491755:ios:bc968a2da2e5d50a9c282e',
    messagingSenderId: '357186491755',
    projectId: 'fir-login-c3535',
    storageBucket: 'fir-login-c3535.appspot.com',
    iosClientId: '357186491755-e19mkqk6fjciajrgup1sr2jvvhsosahn.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCij3-X18MRhfUQF7J09kXjK2V4EgRSWyU',
    appId: '1:357186491755:ios:bc968a2da2e5d50a9c282e',
    messagingSenderId: '357186491755',
    projectId: 'fir-login-c3535',
    storageBucket: 'fir-login-c3535.appspot.com',
    iosClientId: '357186491755-e19mkqk6fjciajrgup1sr2jvvhsosahn.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginfirebase',
  );
}
